---
- name: Install MySQL and create a db user
  hosts: dbservers
  vars_files:

  tasks:
    - name: install mysql server
      apt:
        name: mysql-server
        state: present
      notify: Start mysql-service

    - name: ensure mysql-service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: install Python mysql lib.
      apt:
        name: python3-mysqldb
        state: present

    - name: Create mysql user
      mysql_user:
        name: dbuser
        host: "%"
        password: "{{ db_password }}"
        priv: '*.*:CREATE,INSERT,UPDATE,DELETE,SELECT'
        state: present

  handlers:
    - name: Start mysql-service
      service:
        name: mysql
        state: started
