- name: Configure and deploy website with Nginx
  hosts: webserver
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # For Debian-based systems like Ubuntu

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy sample website
      template:
        src: /home/yousry/Ansbile/lab5/index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

