---
- hosts: all
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/yousry/Downloads/lab26.pem
  tasks:
    - name: Ensure Python is installed
      ansible.builtin.package:
        name: python3
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu' 



