---
- name: Install Java
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  tags:
  ---
- name: Install Java
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  tags:
  ---
- name: Install Java
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  tags:
    - jenkins

- name: Add Jenkins Debian repository
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  tags:
    - jenkins

  become: yes
  apt:
    name: jenkins
    state: present
  tags:
    - jenkins

